const data = {
  copyright: 'NHL and the NHL Shield are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2019. All Rights Reserved.',
  stats: [{
    type: {
      displayName: 'yearByYear',
    },
    splits: [{
      season: '20092010',
      stat: {
        assists: 45,
        goals: 24,
        pim: 72,
        games: 42,
        penaltyMinutes: '72',
        plusMinus: 0,
        points: 69,
      },
      team: {
        name: 'Sudbury Wolves Bantam AAA',
        link: '/api/v1/teams/null',
      },
      league: {
        name: 'NOBHL',
        link: '/api/v1/league/null',
      },
      sequenceNumber: 110042,
    }, {
      season: '20102011',
      stat: {
        assists: 45,
        goals: 20,
        pim: 58,
        games: 32,
        penaltyMinutes: '58',
        points: 65,
      },
      team: {
        name: 'Sud. Wolves M.M.',
        link: '/api/v1/teams/null',
      },
      league: {
        name: 'Minor-ON',
        link: '/api/v1/league/null',
      },
      sequenceNumber: 1,
    }, {
      season: '20102011',
      stat: {
        assists: 1,
        goals: 1,
        pim: 12,
        games: 3,
        penaltyMinutes: '12',
        points: 2,
      },
      team: {
        name: 'Sud. Wolves Mid.',
        link: '/api/v1/teams/null',
      },
      league: {
        name: 'Minor-ON',
        link: '/api/v1/league/null',
      },
      sequenceNumber: 2,
    }, {
      season: '20112012',
      stat: {
        assists: 11,
        goals: 6,
        pim: 117,
        games: 61,
        powerPlayGoals: 1,
        penaltyMinutes: '117',
        shortHandedGoals: 0,
        plusMinus: 2,
        points: 17,
      },
      team: {
        id: 1870,
        name: 'Guelph',
        link: '/api/v1/teams/1870',
      },
      league: {
        id: 141,
        name: 'OHL',
        link: '/api/v1/league/141',
      },
      sequenceNumber: 1,
    }, {
      season: '20122013',
      stat: {
        assists: 9,
        goals: 13,
        pim: 68,
        games: 43,
        powerPlayGoals: 2,
        penaltyMinutes: '68',
        shortHandedGoals: 0,
        plusMinus: -2,
        points: 22,
      },
      team: {
        id: 1870,
        name: 'Guelph',
        link: '/api/v1/teams/1870',
      },
      league: {
        id: 141,
        name: 'OHL',
        link: '/api/v1/league/141',
      },
      sequenceNumber: 1,
    }, {
      season: '20132014',
      stat: {
        assists: 26,
        goals: 9,
        pim: 49,
        games: 29,
        powerPlayGoals: 4,
        penaltyMinutes: '49',
        gameWinningGoals: 2,
        shortHandedGoals: 0,
        plusMinus: 9,
        points: 35,
      },
      team: {
        id: 1870,
        name: 'Guelph',
        link: '/api/v1/teams/1870',
      },
      league: {
        id: 141,
        name: 'OHL',
        link: '/api/v1/league/141',
      },
      sequenceNumber: 1,
    }, {
      season: '20142015',
      stat: {
        assists: 55,
        goals: 43,
        pim: 91,
        games: 68,
        powerPlayGoals: 13,
        penaltyMinutes: '91',
        gameWinningGoals: 5,
        shortHandedGoals: 0,
        plusMinus: 26,
        points: 98,
      },
      team: {
        id: 1870,
        name: 'Guelph',
        link: '/api/v1/teams/1870',
      },
      league: {
        id: 141,
        name: 'OHL',
        link: '/api/v1/league/141',
      },
      sequenceNumber: 1,
    }, {
      season: '20142015',
      stat: {
        assists: 0,
        goals: 1,
        pim: 0,
        shots: 4,
        games: 2,
        powerPlayGoals: 0,
        penaltyMinutes: '0',
        shotPct: 25.0,
        gameWinningGoals: 0,
        shortHandedGoals: 0,
        plusMinus: -2,
        points: 1,
      },
      team: {
        id: 6840,
        name: 'Grand Rapids',
        link: '/api/v1/teams/6840',
      },
      league: {
        id: 153,
        name: 'AHL',
        link: '/api/v1/league/153',
      },
      sequenceNumber: 2,
    }, {
      season: '20152016',
      stat: {
        assists: 18,
        goals: 12,
        pim: 133,
        shots: 148,
        games: 71,
        powerPlayGoals: 4,
        penaltyMinutes: '133',
        shotPct: 8.1,
        gameWinningGoals: 1,
        shortHandedGoals: 0,
        plusMinus: 7,
        points: 30,
      },
      team: {
        id: 6840,
        name: 'Grand Rapids',
        link: '/api/v1/teams/6840',
      },
      league: {
        name: 'AHL',
        link: '/api/v1/league/null',
      },
      sequenceNumber: 1,
    }, {
      season: '20162017',
      stat: {
        timeOnIce: '63:45',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 3,
        games: 7,
        hits: 12,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:22',
        evenTimeOnIce: '63:23',
        penaltyMinutes: '0',
        faceOffPct: 50.0,
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: -1,
        points: 0,
        shifts: 90,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      league: {
        id: 133,
        name: 'National Hockey League',
        link: '/api/v1/league/133',
      },
      sequenceNumber: 1,
    }, {
      season: '20162017',
      stat: {
        assists: 25,
        goals: 12,
        pim: 37,
        games: 48,
        penaltyMinutes: '37',
        plusMinus: 15,
        points: 37,
      },
      team: {
        name: 'Grand Rapids Griffins',
        link: '/api/v1/teams/null',
      },
      league: {
        name: 'AHL',
        link: '/api/v1/league/null',
      },
      sequenceNumber: 978,
    }, {
      season: '20172018',
      stat: {
        timeOnIce: '691:12',
        assists: 17,
        goals: 7,
        pim: 39,
        shots: 83,
        games: 48,
        hits: 53,
        powerPlayGoals: 1,
        powerPlayPoints: 2,
        powerPlayTimeOnIce: '68:25',
        evenTimeOnIce: '617:34',
        penaltyMinutes: '39',
        faceOffPct: 12.5,
        shotPct: 8.4,
        gameWinningGoals: 1,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '05:13',
        blocked: 38,
        plusMinus: -7,
        points: 24,
        shifts: 901,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      league: {
        id: 133,
        name: 'National Hockey League',
        link: '/api/v1/league/133',
      },
      sequenceNumber: 1,
    }, {
      season: '20172018',
      stat: {
        assists: 7,
        goals: 7,
        pim: 34,
        games: 16,
        penaltyMinutes: '34',
        plusMinus: -5,
        points: 14,
      },
      team: {
        name: 'Grand Rapids Griffins',
        link: '/api/v1/teams/null',
      },
      league: {
        name: 'AHL',
        link: '/api/v1/league/null',
      },
      sequenceNumber: 978,
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '1205:41',
        assists: 26,
        goals: 21,
        pim: 36,
        shots: 131,
        games: 73,
        hits: 76,
        powerPlayGoals: 3,
        powerPlayPoints: 6,
        powerPlayTimeOnIce: '125:29',
        evenTimeOnIce: '1079:01',
        penaltyMinutes: '36',
        faceOffPct: 33.33,
        shotPct: 16.0,
        gameWinningGoals: 4,
        overTimeGoals: 1,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '01:11',
        blocked: 39,
        plusMinus: 11,
        points: 47,
        shifts: 1547,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      league: {
        id: 133,
        name: 'National Hockey League',
        link: '/api/v1/league/133',
      },
      sequenceNumber: 1,
    }],
  }, {
    type: {
      displayName: 'careerRegularSeason',
    },
    splits: [{
      stat: {
        timeOnIce: '1960:38',
        assists: 43,
        goals: 28,
        pim: 75,
        shots: 217,
        games: 128,
        hits: 141,
        powerPlayGoals: 4,
        powerPlayPoints: 8,
        powerPlayTimeOnIce: '194:16',
        evenTimeOnIce: '1759:58',
        penaltyMinutes: '75',
        faceOffPct: 30.0,
        shotPct: 12.9,
        gameWinningGoals: 5,
        overTimeGoals: 1,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '06:24',
        blocked: 77,
        plusMinus: 3,
        points: 71,
        shifts: 2538,
        timeOnIcePerGame: '15:19',
        evenTimeOnIcePerGame: '13:44',
        shortHandedTimeOnIcePerGame: '00:03',
        powerPlayTimeOnIcePerGame: '01:31',
      },
    }],
  }, {
    type: {
      displayName: 'yearByYearPlayoffs',
    },
    splits: [{
      season: '20102011',
      stat: {
        assists: 0,
        goals: 0,
        pim: 12,
        games: 2,
        penaltyMinutes: '12',
        points: 0,
      },
      team: {
        name: 'Sud. Wolves Mid.',
        link: '/api/v1/teams/null',
      },
      league: {
        name: 'Minor-ON',
        link: '/api/v1/league/null',
      },
      sequenceNumber: 2,
    }, {
      season: '20112012',
      stat: {
        assists: 2,
        goals: 0,
        pim: 7,
        games: 6,
        powerPlayGoals: 0,
        penaltyMinutes: '7',
        shortHandedGoals: 0,
        plusMinus: 0,
        points: 2,
      },
      team: {
        id: 1870,
        name: 'Guelph',
        link: '/api/v1/teams/1870',
      },
      league: {
        id: 141,
        name: 'OHL',
        link: '/api/v1/league/141',
      },
      sequenceNumber: 1,
    }, {
      season: '20122013',
      stat: {
        assists: 0,
        goals: 0,
        pim: 14,
        games: 5,
        powerPlayGoals: 0,
        penaltyMinutes: '14',
        shortHandedGoals: 0,
        plusMinus: 0,
        points: 0,
      },
      team: {
        id: 1870,
        name: 'Guelph',
        link: '/api/v1/teams/1870',
      },
      league: {
        id: 141,
        name: 'OHL',
        link: '/api/v1/league/141',
      },
      sequenceNumber: 1,
    }, {
      season: '20132014',
      stat: {
        assists: 7,
        goals: 10,
        pim: 24,
        games: 18,
        powerPlayGoals: 0,
        penaltyMinutes: '24',
        gameWinningGoals: 0,
        shortHandedGoals: 0,
        plusMinus: 14,
        points: 17,
      },
      team: {
        id: 1870,
        name: 'Guelph',
        link: '/api/v1/teams/1870',
      },
      league: {
        id: 141,
        name: 'OHL',
        link: '/api/v1/league/141',
      },
      sequenceNumber: 1,
    }, {
      season: '20132014',
      stat: {
        assists: 0,
        goals: 5,
        pim: 10,
        games: 4,
        powerPlayGoals: 1,
        penaltyMinutes: '10',
        gameWinningGoals: 1,
        shortHandedGoals: 0,
        plusMinus: 3,
        points: 5,
      },
      team: {
        id: 1870,
        name: 'Guelph',
        link: '/api/v1/teams/1870',
      },
      league: {
        id: 141,
        name: 'M-Cup',
        link: '/api/v1/league/141',
      },
      sequenceNumber: 2,
    }, {
      season: '20142015',
      stat: {
        assists: 2,
        goals: 6,
        pim: 10,
        games: 9,
        powerPlayGoals: 3,
        penaltyMinutes: '10',
        gameWinningGoals: 0,
        shortHandedGoals: 0,
        plusMinus: -5,
        points: 8,
      },
      team: {
        id: 1870,
        name: 'Guelph',
        link: '/api/v1/teams/1870',
      },
      league: {
        id: 141,
        name: 'OHL',
        link: '/api/v1/league/141',
      },
      sequenceNumber: 1,
    }, {
      season: '20142015',
      stat: {
        assists: 5,
        goals: 7,
        pim: 10,
        shots: 29,
        games: 14,
        powerPlayGoals: 1,
        penaltyMinutes: '10',
        shotPct: 24.1,
        gameWinningGoals: 4,
        shortHandedGoals: 0,
        plusMinus: 4,
        points: 12,
      },
      team: {
        id: 6840,
        name: 'Grand Rapids',
        link: '/api/v1/teams/6840',
      },
      league: {
        id: 153,
        name: 'AHL',
        link: '/api/v1/league/153',
      },
      sequenceNumber: 2,
    }, {
      season: '20152016',
      stat: {
        assists: 1,
        goals: 7,
        pim: 8,
        shots: 20,
        games: 9,
        powerPlayGoals: 1,
        penaltyMinutes: '8',
        shotPct: 35.0,
        gameWinningGoals: 2,
        shortHandedGoals: 0,
        plusMinus: 7,
        points: 8,
      },
      team: {
        id: 6840,
        name: 'Grand Rapids',
        link: '/api/v1/teams/6840',
      },
      league: {
        name: 'AHL',
        link: '/api/v1/league/null',
      },
      sequenceNumber: 1,
    }, {
      season: '20162017',
      stat: {
        assists: 10,
        goals: 9,
        pim: 50,
        games: 19,
        penaltyMinutes: '50',
        plusMinus: 1,
        points: 19,
      },
      team: {
        name: 'Grand Rapids Griffins',
        link: '/api/v1/teams/null',
      },
      league: {
        name: 'AHL',
        link: '/api/v1/league/null',
      },
      sequenceNumber: 978,
    }],
  }, {
    type: {
      displayName: 'careerPlayoffs',
    },
    splits: [],
  }, {
    type: {
      displayName: 'gameLog',
    },
    splits: [{
      season: '20182019',
      stat: {
        timeOnIce: '21:37',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 2,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '03:52',
        evenTimeOnIce: '17:45',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: -1,
        points: 0,
        shifts: 22,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 7,
        name: 'Buffalo Sabres',
        link: '/api/v1/teams/7',
      },
      date: '2019-04-06',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018021261,
        link: '/api/v1/game/2018021261/feed/live',
        content: {
          link: '/api/v1/game/2018021261/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '20:25',
        assists: 0,
        goals: 0,
        pim: 4,
        shots: 4,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:40',
        evenTimeOnIce: '17:45',
        penaltyMinutes: '4',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: -1,
        points: 0,
        shifts: 24,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 5,
        name: 'Pittsburgh Penguins',
        link: '/api/v1/teams/5',
      },
      date: '2019-04-04',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018021245,
        link: '/api/v1/game/2018021245/feed/live',
        content: {
          link: '/api/v1/game/2018021245/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '19:26',
        assists: 1,
        goals: 2,
        pim: 0,
        shots: 5,
        games: 1,
        hits: 0,
        powerPlayGoals: 1,
        powerPlayPoints: 1,
        powerPlayTimeOnIce: '00:22',
        evenTimeOnIce: '18:48',
        penaltyMinutes: '0',
        shotPct: 40.0,
        gameWinningGoals: 1,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:16',
        blocked: 0,
        plusMinus: 2,
        points: 3,
        shifts: 27,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 5,
        name: 'Pittsburgh Penguins',
        link: '/api/v1/teams/5',
      },
      date: '2019-04-02',
      isHome: true,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018021233,
        link: '/api/v1/game/2018021233/feed/live',
        content: {
          link: '/api/v1/game/2018021233/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:18',
        assists: 3,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 2,
        powerPlayTimeOnIce: '04:20',
        evenTimeOnIce: '11:51',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:07',
        blocked: 1,
        plusMinus: 1,
        points: 3,
        shifts: 22,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 6,
        name: 'Boston Bruins',
        link: '/api/v1/teams/6',
      },
      date: '2019-03-31',
      isHome: true,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018021219,
        link: '/api/v1/game/2018021219/feed/live',
        content: {
          link: '/api/v1/game/2018021219/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:19',
        assists: 2,
        goals: 1,
        pim: 0,
        shots: 4,
        games: 1,
        hits: 2,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:00',
        evenTimeOnIce: '15:19',
        penaltyMinutes: '0',
        shotPct: 25.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 3,
        points: 3,
        shifts: 20,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 1,
        name: 'New Jersey Devils',
        link: '/api/v1/teams/1',
      },
      date: '2019-03-29',
      isHome: true,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018021199,
        link: '/api/v1/game/2018021199/feed/live',
        content: {
          link: '/api/v1/game/2018021199/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:58',
        assists: 1,
        goals: 2,
        pim: 0,
        shots: 4,
        games: 1,
        hits: 0,
        powerPlayGoals: 1,
        powerPlayPoints: 1,
        powerPlayTimeOnIce: '02:46',
        evenTimeOnIce: '14:12',
        penaltyMinutes: '0',
        shotPct: 50.0,
        gameWinningGoals: 1,
        overTimeGoals: 1,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 1,
        points: 3,
        shifts: 21,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 7,
        name: 'Buffalo Sabres',
        link: '/api/v1/teams/7',
      },
      date: '2019-03-28',
      isHome: false,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018021189,
        link: '/api/v1/game/2018021189/feed/live',
        content: {
          link: '/api/v1/game/2018021189/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '18:39',
        assists: 1,
        goals: 0,
        pim: 0,
        shots: 3,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:06',
        evenTimeOnIce: '17:33',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 1,
        points: 1,
        shifts: 23,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 28,
        name: 'San Jose Sharks',
        link: '/api/v1/teams/28',
      },
      date: '2019-03-25',
      isHome: false,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018021177,
        link: '/api/v1/game/2018021177/feed/live',
        content: {
          link: '/api/v1/game/2018021177/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '19:18',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:12',
        evenTimeOnIce: '17:55',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:11',
        blocked: 0,
        plusMinus: -1,
        points: 0,
        shifts: 25,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 54,
        name: 'Vegas Golden Knights',
        link: '/api/v1/teams/54',
      },
      date: '2019-03-23',
      isHome: false,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018021162,
        link: '/api/v1/game/2018021162/feed/live',
        content: {
          link: '/api/v1/game/2018021162/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:54',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 0,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:40',
        evenTimeOnIce: '16:14',
        penaltyMinutes: '0',
        faceOffPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 0,
        points: 0,
        shifts: 21,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 19,
        name: 'St. Louis Blues',
        link: '/api/v1/teams/19',
      },
      date: '2019-03-21',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018021140,
        link: '/api/v1/game/2018021140/feed/live',
        content: {
          link: '/api/v1/game/2018021140/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '18:18',
        assists: 0,
        goals: 0,
        pim: 2,
        shots: 0,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:30',
        evenTimeOnIce: '17:48',
        penaltyMinutes: '2',
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 1,
        points: 0,
        shifts: 21,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 3,
        name: 'New York Rangers',
        link: '/api/v1/teams/3',
      },
      date: '2019-03-19',
      isHome: false,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018021124,
        link: '/api/v1/game/2018021124/feed/live',
        content: {
          link: '/api/v1/game/2018021124/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '20:05',
        assists: 1,
        goals: 0,
        pim: 0,
        shots: 3,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '03:24',
        evenTimeOnIce: '16:41',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 2,
        points: 1,
        shifts: 22,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 2,
        name: 'New York Islanders',
        link: '/api/v1/teams/2',
      },
      date: '2019-03-16',
      isHome: true,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018021100,
        link: '/api/v1/game/2018021100/feed/live',
        content: {
          link: '/api/v1/game/2018021100/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '20:06',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 3,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '03:39',
        evenTimeOnIce: '16:27',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: 0,
        points: 0,
        shifts: 23,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 14,
        name: 'Tampa Bay Lightning',
        link: '/api/v1/teams/14',
      },
      date: '2019-03-14',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018021087,
        link: '/api/v1/game/2018021087/feed/live',
        content: {
          link: '/api/v1/game/2018021087/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '15:57',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:35',
        evenTimeOnIce: '13:22',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: -2,
        points: 0,
        shifts: 18,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 8,
        name: 'Montréal Canadiens',
        link: '/api/v1/teams/8',
      },
      date: '2019-03-12',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018021075,
        link: '/api/v1/game/2018021075/feed/live',
        content: {
          link: '/api/v1/game/2018021075/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '18:22',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 3,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:12',
        evenTimeOnIce: '16:10',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: -1,
        points: 0,
        shifts: 23,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 13,
        name: 'Florida Panthers',
        link: '/api/v1/teams/13',
      },
      date: '2019-03-10',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018021060,
        link: '/api/v1/game/2018021060/feed/live',
        content: {
          link: '/api/v1/game/2018021060/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '17:18',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '04:45',
        evenTimeOnIce: '12:33',
        penaltyMinutes: '0',
        faceOffPct: 0.0,
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: -1,
        points: 0,
        shifts: 20,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 14,
        name: 'Tampa Bay Lightning',
        link: '/api/v1/teams/14',
      },
      date: '2019-03-09',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018021051,
        link: '/api/v1/game/2018021051/feed/live',
        content: {
          link: '/api/v1/game/2018021051/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '20:31',
        assists: 0,
        goals: 1,
        pim: 0,
        shots: 4,
        games: 1,
        hits: 2,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:35',
        evenTimeOnIce: '17:56',
        penaltyMinutes: '0',
        shotPct: 25.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 0,
        points: 1,
        shifts: 26,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 3,
        name: 'New York Rangers',
        link: '/api/v1/teams/3',
      },
      date: '2019-03-07',
      isHome: true,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018021036,
        link: '/api/v1/game/2018021036/feed/live',
        content: {
          link: '/api/v1/game/2018021036/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '18:53',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '03:06',
        evenTimeOnIce: '15:47',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 1,
        points: 0,
        shifts: 22,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 21,
        name: 'Colorado Avalanche',
        link: '/api/v1/teams/21',
      },
      date: '2019-03-05',
      isHome: false,
      isWin: false,
      isOT: true,
      game: {
        gamePk: 2018021026,
        link: '/api/v1/game/2018021026/feed/live',
        content: {
          link: '/api/v1/game/2018021026/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:39',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:58',
        evenTimeOnIce: '15:41',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 2,
        plusMinus: -2,
        points: 0,
        shifts: 20,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 53,
        name: 'Arizona Coyotes',
        link: '/api/v1/teams/53',
      },
      date: '2019-03-02',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018021007,
        link: '/api/v1/game/2018021007/feed/live',
        content: {
          link: '/api/v1/game/2018021007/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:39',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '03:23',
        evenTimeOnIce: '13:16',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: -1,
        points: 0,
        shifts: 22,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 8,
        name: 'Montréal Canadiens',
        link: '/api/v1/teams/8',
      },
      date: '2019-02-26',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020974,
        link: '/api/v1/game/2018020974/feed/live',
        content: {
          link: '/api/v1/game/2018020974/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:33',
        assists: 1,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 2,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:54',
        evenTimeOnIce: '15:39',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 2,
        plusMinus: 0,
        points: 1,
        shifts: 21,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 28,
        name: 'San Jose Sharks',
        link: '/api/v1/teams/28',
      },
      date: '2019-02-24',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020957,
        link: '/api/v1/game/2018020957/feed/live',
        content: {
          link: '/api/v1/game/2018020957/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '19:28',
        assists: 0,
        goals: 1,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:04',
        evenTimeOnIce: '18:24',
        penaltyMinutes: '0',
        shotPct: 50.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: 1,
        points: 1,
        shifts: 23,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 30,
        name: 'Minnesota Wild',
        link: '/api/v1/teams/30',
      },
      date: '2019-02-22',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020941,
        link: '/api/v1/game/2018020941/feed/live',
        content: {
          link: '/api/v1/game/2018020941/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '18:32',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 5,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:26',
        evenTimeOnIce: '16:06',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 2,
        points: 0,
        shifts: 24,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 16,
        name: 'Chicago Blackhawks',
        link: '/api/v1/teams/16',
      },
      date: '2019-02-20',
      isHome: true,
      isWin: false,
      isOT: true,
      game: {
        gamePk: 2018020925,
        link: '/api/v1/game/2018020925/feed/live',
        content: {
          link: '/api/v1/game/2018020925/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '19:26',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 3,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:29',
        evenTimeOnIce: '18:57',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: -1,
        points: 0,
        shifts: 21,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 4,
        name: 'Philadelphia Flyers',
        link: '/api/v1/teams/4',
      },
      date: '2019-02-17',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020907,
        link: '/api/v1/game/2018020907/feed/live',
        content: {
          link: '/api/v1/game/2018020907/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '19:32',
        assists: 1,
        goals: 1,
        pim: 0,
        shots: 3,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:01',
        evenTimeOnIce: '18:31',
        penaltyMinutes: '0',
        shotPct: 33.3,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 0,
        points: 2,
        shifts: 27,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 4,
        name: 'Philadelphia Flyers',
        link: '/api/v1/teams/4',
      },
      date: '2019-02-16',
      isHome: false,
      isWin: false,
      isOT: true,
      game: {
        gamePk: 2018020892,
        link: '/api/v1/game/2018020892/feed/live',
        content: {
          link: '/api/v1/game/2018020892/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '11:57',
        assists: 1,
        goals: 0,
        pim: 0,
        shots: 3,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:43',
        evenTimeOnIce: '10:14',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 1,
        points: 1,
        shifts: 18,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 22,
        name: 'Edmonton Oilers',
        link: '/api/v1/teams/22',
      },
      date: '2019-01-22',
      isHome: false,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020764,
        link: '/api/v1/game/2018020764/feed/live',
        content: {
          link: '/api/v1/game/2018020764/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '18:34',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 3,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:16',
        evenTimeOnIce: '17:18',
        penaltyMinutes: '0',
        faceOffPct: 0.0,
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: -1,
        points: 0,
        shifts: 24,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 23,
        name: 'Vancouver Canucks',
        link: '/api/v1/teams/23',
      },
      date: '2019-01-20',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020753,
        link: '/api/v1/game/2018020753/feed/live',
        content: {
          link: '/api/v1/game/2018020753/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '17:19',
        assists: 2,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 2,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:33',
        evenTimeOnIce: '14:46',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 2,
        points: 2,
        shifts: 25,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 20,
        name: 'Calgary Flames',
        link: '/api/v1/teams/20',
      },
      date: '2019-01-18',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020737,
        link: '/api/v1/game/2018020737/feed/live',
        content: {
          link: '/api/v1/game/2018020737/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '18:26',
        assists: 0,
        goals: 0,
        pim: 2,
        shots: 1,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:00',
        evenTimeOnIce: '18:26',
        penaltyMinutes: '2',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 1,
        points: 0,
        shifts: 21,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 24,
        name: 'Anaheim Ducks',
        link: '/api/v1/teams/24',
      },
      date: '2019-01-15',
      isHome: true,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020715,
        link: '/api/v1/game/2018020715/feed/live',
        content: {
          link: '/api/v1/game/2018020715/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '15:32',
        assists: 0,
        goals: 3,
        pim: 0,
        shots: 5,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:29',
        evenTimeOnIce: '15:03',
        penaltyMinutes: '0',
        faceOffPct: 100.0,
        shotPct: 60.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: 3,
        points: 3,
        shifts: 19,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 30,
        name: 'Minnesota Wild',
        link: '/api/v1/teams/30',
      },
      date: '2019-01-12',
      isHome: false,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020693,
        link: '/api/v1/game/2018020693/feed/live',
        content: {
          link: '/api/v1/game/2018020693/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '15:52',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 3,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:48',
        evenTimeOnIce: '14:04',
        penaltyMinutes: '0',
        faceOffPct: 0.0,
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 0,
        points: 0,
        shifts: 20,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 52,
        name: 'Winnipeg Jets',
        link: '/api/v1/teams/52',
      },
      date: '2019-01-11',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020684,
        link: '/api/v1/game/2018020684/feed/live',
        content: {
          link: '/api/v1/game/2018020684/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '14:00',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '03:22',
        evenTimeOnIce: '10:38',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 0,
        points: 0,
        shifts: 17,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 8,
        name: 'Montréal Canadiens',
        link: '/api/v1/teams/8',
      },
      date: '2019-01-08',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020662,
        link: '/api/v1/game/2018020662/feed/live',
        content: {
          link: '/api/v1/game/2018020662/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '14:36',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 0,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:26',
        evenTimeOnIce: '13:10',
        penaltyMinutes: '0',
        faceOffPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: 0,
        points: 0,
        shifts: 21,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 15,
        name: 'Washington Capitals',
        link: '/api/v1/teams/15',
      },
      date: '2019-01-06',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020648,
        link: '/api/v1/game/2018020648/feed/live',
        content: {
          link: '/api/v1/game/2018020648/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:41',
        assists: 0,
        goals: 1,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:13',
        evenTimeOnIce: '15:28',
        penaltyMinutes: '0',
        shotPct: 50.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 2,
        plusMinus: 0,
        points: 1,
        shifts: 23,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 18,
        name: 'Nashville Predators',
        link: '/api/v1/teams/18',
      },
      date: '2019-01-04',
      isHome: true,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020630,
        link: '/api/v1/game/2018020630/feed/live',
        content: {
          link: '/api/v1/game/2018020630/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '17:50',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 0,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:38',
        evenTimeOnIce: '17:12',
        penaltyMinutes: '0',
        faceOffPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: -1,
        points: 0,
        shifts: 20,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 20,
        name: 'Calgary Flames',
        link: '/api/v1/teams/20',
      },
      date: '2019-01-02',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020616,
        link: '/api/v1/game/2018020616/feed/live',
        content: {
          link: '/api/v1/game/2018020616/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:00',
        assists: 1,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:34',
        evenTimeOnIce: '14:26',
        penaltyMinutes: '0',
        faceOffPct: 100.0,
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: 1,
        points: 1,
        shifts: 21,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 13,
        name: 'Florida Panthers',
        link: '/api/v1/teams/13',
      },
      date: '2018-12-31',
      isHome: true,
      isWin: false,
      isOT: true,
      game: {
        gamePk: 2018020606,
        link: '/api/v1/game/2018020606/feed/live',
        content: {
          link: '/api/v1/game/2018020606/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '15:08',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:53',
        evenTimeOnIce: '12:15',
        penaltyMinutes: '0',
        faceOffPct: 50.0,
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 0,
        points: 0,
        shifts: 19,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 25,
        name: 'Dallas Stars',
        link: '/api/v1/teams/25',
      },
      date: '2018-12-29',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020594,
        link: '/api/v1/game/2018020594/feed/live',
        content: {
          link: '/api/v1/game/2018020594/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '15:15',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 3,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:47',
        evenTimeOnIce: '14:28',
        penaltyMinutes: '0',
        faceOffPct: 0.0,
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: -1,
        points: 0,
        shifts: 19,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 5,
        name: 'Pittsburgh Penguins',
        link: '/api/v1/teams/5',
      },
      date: '2018-12-27',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020569,
        link: '/api/v1/game/2018020569/feed/live',
        content: {
          link: '/api/v1/game/2018020569/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '19:31',
        assists: 1,
        goals: 0,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:18',
        evenTimeOnIce: '18:13',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: 1,
        points: 1,
        shifts: 28,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 10,
        name: 'Toronto Maple Leafs',
        link: '/api/v1/teams/10',
      },
      date: '2018-12-23',
      isHome: false,
      isWin: false,
      isOT: true,
      game: {
        gamePk: 2018020563,
        link: '/api/v1/game/2018020563/feed/live',
        content: {
          link: '/api/v1/game/2018020563/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:18',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:39',
        evenTimeOnIce: '13:39',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 2,
        plusMinus: 1,
        points: 0,
        shifts: 20,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 13,
        name: 'Florida Panthers',
        link: '/api/v1/teams/13',
      },
      date: '2018-12-22',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020547,
        link: '/api/v1/game/2018020547/feed/live',
        content: {
          link: '/api/v1/game/2018020547/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:24',
        assists: 1,
        goals: 0,
        pim: 0,
        shots: 0,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:29',
        evenTimeOnIce: '15:55',
        penaltyMinutes: '0',
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: 1,
        points: 1,
        shifts: 23,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 12,
        name: 'Carolina Hurricanes',
        link: '/api/v1/teams/12',
      },
      date: '2018-12-20',
      isHome: false,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020534,
        link: '/api/v1/game/2018020534/feed/live',
        content: {
          link: '/api/v1/game/2018020534/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '14:55',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:04',
        evenTimeOnIce: '14:51',
        penaltyMinutes: '0',
        faceOffPct: 0.0,
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: -1,
        points: 0,
        shifts: 19,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 4,
        name: 'Philadelphia Flyers',
        link: '/api/v1/teams/4',
      },
      date: '2018-12-18',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020520,
        link: '/api/v1/game/2018020520/feed/live',
        content: {
          link: '/api/v1/game/2018020520/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:42',
        assists: 1,
        goals: 0,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:00',
        evenTimeOnIce: '16:42',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 1,
        points: 1,
        shifts: 23,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 2,
        name: 'New York Islanders',
        link: '/api/v1/teams/2',
      },
      date: '2018-12-15',
      isHome: false,
      isWin: false,
      isOT: true,
      game: {
        gamePk: 2018020498,
        link: '/api/v1/game/2018020498/feed/live',
        content: {
          link: '/api/v1/game/2018020498/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '13:51',
        assists: 1,
        goals: 0,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:10',
        evenTimeOnIce: '13:41',
        penaltyMinutes: '0',
        faceOffPct: 100.0,
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: -1,
        points: 1,
        shifts: 21,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 9,
        name: 'Ottawa Senators',
        link: '/api/v1/teams/9',
      },
      date: '2018-12-14',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020490,
        link: '/api/v1/game/2018020490/feed/live',
        content: {
          link: '/api/v1/game/2018020490/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:44',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:47',
        evenTimeOnIce: '15:57',
        penaltyMinutes: '0',
        faceOffPct: 0.0,
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: -1,
        points: 0,
        shifts: 22,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 15,
        name: 'Washington Capitals',
        link: '/api/v1/teams/15',
      },
      date: '2018-12-11',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020467,
        link: '/api/v1/game/2018020467/feed/live',
        content: {
          link: '/api/v1/game/2018020467/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:38',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 0,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:00',
        evenTimeOnIce: '16:38',
        penaltyMinutes: '0',
        faceOffPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 2,
        plusMinus: -1,
        points: 0,
        shifts: 22,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 26,
        name: 'Los Angeles Kings',
        link: '/api/v1/teams/26',
      },
      date: '2018-12-10',
      isHome: true,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020462,
        link: '/api/v1/game/2018020462/feed/live',
        content: {
          link: '/api/v1/game/2018020462/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '17:02',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 2,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:02',
        evenTimeOnIce: '15:00',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 0,
        points: 0,
        shifts: 22,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 2,
        name: 'New York Islanders',
        link: '/api/v1/teams/2',
      },
      date: '2018-12-08',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020448,
        link: '/api/v1/game/2018020448/feed/live',
        content: {
          link: '/api/v1/game/2018020448/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '14:53',
        assists: 0,
        goals: 0,
        pim: 5,
        shots: 1,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:51',
        evenTimeOnIce: '13:02',
        penaltyMinutes: '5',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: 0,
        points: 0,
        shifts: 19,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 21,
        name: 'Colorado Avalanche',
        link: '/api/v1/teams/21',
      },
      date: '2018-12-02',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020410,
        link: '/api/v1/game/2018020410/feed/live',
        content: {
          link: '/api/v1/game/2018020410/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '13:37',
        assists: 0,
        goals: 1,
        pim: 2,
        shots: 3,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:16',
        evenTimeOnIce: '12:20',
        penaltyMinutes: '2',
        faceOffPct: 50.0,
        shotPct: 33.3,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:01',
        blocked: 0,
        plusMinus: 2,
        points: 1,
        shifts: 23,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 6,
        name: 'Boston Bruins',
        link: '/api/v1/teams/6',
      },
      date: '2018-12-01',
      isHome: false,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020397,
        link: '/api/v1/game/2018020397/feed/live',
        content: {
          link: '/api/v1/game/2018020397/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:21',
        assists: 0,
        goals: 2,
        pim: 2,
        shots: 3,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:45',
        evenTimeOnIce: '15:36',
        penaltyMinutes: '2',
        shotPct: 66.7,
        gameWinningGoals: 1,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 2,
        plusMinus: 2,
        points: 2,
        shifts: 18,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 19,
        name: 'St. Louis Blues',
        link: '/api/v1/teams/19',
      },
      date: '2018-11-28',
      isHome: true,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020377,
        link: '/api/v1/game/2018020377/feed/live',
        content: {
          link: '/api/v1/game/2018020377/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '12:58',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 2,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:06',
        evenTimeOnIce: '12:52',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: -1,
        points: 0,
        shifts: 19,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 29,
        name: 'Columbus Blue Jackets',
        link: '/api/v1/teams/29',
      },
      date: '2018-11-26',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020366,
        link: '/api/v1/game/2018020366/feed/live',
        content: {
          link: '/api/v1/game/2018020366/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '15:17',
        assists: 1,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 2,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '03:14',
        evenTimeOnIce: '12:03',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: 1,
        points: 1,
        shifts: 22,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 7,
        name: 'Buffalo Sabres',
        link: '/api/v1/teams/7',
      },
      date: '2018-11-24',
      isHome: true,
      isWin: false,
      isOT: true,
      game: {
        gamePk: 2018020350,
        link: '/api/v1/game/2018020350/feed/live',
        content: {
          link: '/api/v1/game/2018020350/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '13:41',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 3,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:43',
        evenTimeOnIce: '10:58',
        penaltyMinutes: '0',
        faceOffPct: 0.0,
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: -1,
        points: 0,
        shifts: 16,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 15,
        name: 'Washington Capitals',
        link: '/api/v1/teams/15',
      },
      date: '2018-11-23',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020335,
        link: '/api/v1/game/2018020335/feed/live',
        content: {
          link: '/api/v1/game/2018020335/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '15:58',
        assists: 0,
        goals: 1,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 2,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:00',
        evenTimeOnIce: '15:58',
        penaltyMinutes: '0',
        shotPct: 100.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: 0,
        points: 1,
        shifts: 24,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 6,
        name: 'Boston Bruins',
        link: '/api/v1/teams/6',
      },
      date: '2018-11-21',
      isHome: true,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020324,
        link: '/api/v1/game/2018020324/feed/live',
        content: {
          link: '/api/v1/game/2018020324/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '18:21',
        assists: 2,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 3,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:35',
        evenTimeOnIce: '17:46',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 2,
        points: 2,
        shifts: 23,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 1,
        name: 'New Jersey Devils',
        link: '/api/v1/teams/1',
      },
      date: '2018-11-17',
      isHome: false,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020292,
        link: '/api/v1/game/2018020292/feed/live',
        content: {
          link: '/api/v1/game/2018020292/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '14:05',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 0,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:12',
        evenTimeOnIce: '11:53',
        penaltyMinutes: '0',
        faceOffPct: 100.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 0,
        points: 0,
        shifts: 18,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 9,
        name: 'Ottawa Senators',
        link: '/api/v1/teams/9',
      },
      date: '2018-11-15',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020281,
        link: '/api/v1/game/2018020281/feed/live',
        content: {
          link: '/api/v1/game/2018020281/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '13:12',
        assists: 1,
        goals: 0,
        pim: 0,
        shots: 0,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:15',
        evenTimeOnIce: '10:57',
        penaltyMinutes: '0',
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: 1,
        points: 1,
        shifts: 16,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 53,
        name: 'Arizona Coyotes',
        link: '/api/v1/teams/53',
      },
      date: '2018-11-13',
      isHome: true,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020268,
        link: '/api/v1/game/2018020268/feed/live',
        content: {
          link: '/api/v1/game/2018020268/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '14:48',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 3,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:20',
        evenTimeOnIce: '12:28',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: -1,
        points: 0,
        shifts: 17,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 12,
        name: 'Carolina Hurricanes',
        link: '/api/v1/teams/12',
      },
      date: '2018-11-10',
      isHome: false,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020250,
        link: '/api/v1/game/2018020250/feed/live',
        content: {
          link: '/api/v1/game/2018020250/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '14:54',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 3,
        games: 1,
        hits: 2,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:43',
        evenTimeOnIce: '13:11',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 0,
        points: 0,
        shifts: 17,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 3,
        name: 'New York Rangers',
        link: '/api/v1/teams/3',
      },
      date: '2018-11-09',
      isHome: true,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020238,
        link: '/api/v1/game/2018020238/feed/live',
        content: {
          link: '/api/v1/game/2018020238/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:29',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:05',
        evenTimeOnIce: '15:24',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: -2,
        points: 0,
        shifts: 21,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 23,
        name: 'Vancouver Canucks',
        link: '/api/v1/teams/23',
      },
      date: '2018-11-06',
      isHome: true,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020219,
        link: '/api/v1/game/2018020219/feed/live',
        content: {
          link: '/api/v1/game/2018020219/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '20:07',
        assists: 0,
        goals: 1,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:20',
        evenTimeOnIce: '18:46',
        penaltyMinutes: '0',
        shotPct: 50.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:01',
        blocked: 0,
        plusMinus: 1,
        points: 1,
        shifts: 26,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 22,
        name: 'Edmonton Oilers',
        link: '/api/v1/teams/22',
      },
      date: '2018-11-03',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020197,
        link: '/api/v1/game/2018020197/feed/live',
        content: {
          link: '/api/v1/game/2018020197/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:49',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 3,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:25',
        evenTimeOnIce: '14:24',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: -1,
        points: 0,
        shifts: 22,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 1,
        name: 'New Jersey Devils',
        link: '/api/v1/teams/1',
      },
      date: '2018-11-01',
      isHome: true,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020184,
        link: '/api/v1/game/2018020184/feed/live',
        content: {
          link: '/api/v1/game/2018020184/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '15:29',
        assists: 0,
        goals: 1,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:38',
        evenTimeOnIce: '13:51',
        penaltyMinutes: '0',
        shotPct: 50.0,
        gameWinningGoals: 1,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 2,
        plusMinus: 0,
        points: 1,
        shifts: 22,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 29,
        name: 'Columbus Blue Jackets',
        link: '/api/v1/teams/29',
      },
      date: '2018-10-30',
      isHome: false,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020170,
        link: '/api/v1/game/2018020170/feed/live',
        content: {
          link: '/api/v1/game/2018020170/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '15:50',
        assists: 0,
        goals: 1,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 6,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '01:28',
        evenTimeOnIce: '14:07',
        penaltyMinutes: '0',
        shotPct: 50.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:15',
        blocked: 1,
        plusMinus: 2,
        points: 1,
        shifts: 20,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 25,
        name: 'Dallas Stars',
        link: '/api/v1/teams/25',
      },
      date: '2018-10-28',
      isHome: true,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020160,
        link: '/api/v1/game/2018020160/feed/live',
        content: {
          link: '/api/v1/game/2018020160/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '13:42',
        assists: 0,
        goals: 0,
        pim: 2,
        shots: 2,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:18',
        evenTimeOnIce: '11:24',
        penaltyMinutes: '2',
        faceOffPct: 0.0,
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: -1,
        points: 0,
        shifts: 17,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 52,
        name: 'Winnipeg Jets',
        link: '/api/v1/teams/52',
      },
      date: '2018-10-26',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020145,
        link: '/api/v1/game/2018020145/feed/live',
        content: {
          link: '/api/v1/game/2018020145/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '14:17',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 2,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '03:04',
        evenTimeOnIce: '11:13',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 0,
        points: 0,
        shifts: 20,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 12,
        name: 'Carolina Hurricanes',
        link: '/api/v1/teams/12',
      },
      date: '2018-10-22',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020119,
        link: '/api/v1/game/2018020119/feed/live',
        content: {
          link: '/api/v1/game/2018020119/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:01',
        assists: 0,
        goals: 0,
        pim: 0,
        shots: 1,
        games: 1,
        hits: 2,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:25',
        evenTimeOnIce: '15:36',
        penaltyMinutes: '0',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: -2,
        points: 0,
        shifts: 24,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 13,
        name: 'Florida Panthers',
        link: '/api/v1/teams/13',
      },
      date: '2018-10-20',
      isHome: false,
      isWin: true,
      isOT: false,
      game: {
        gamePk: 2018020108,
        link: '/api/v1/game/2018020108/feed/live',
        content: {
          link: '/api/v1/game/2018020108/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '15:39',
        assists: 0,
        goals: 0,
        pim: 2,
        shots: 0,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '03:22',
        evenTimeOnIce: '12:17',
        penaltyMinutes: '2',
        faceOffPct: 33.33,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 1,
        plusMinus: -1,
        points: 0,
        shifts: 24,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 14,
        name: 'Tampa Bay Lightning',
        link: '/api/v1/teams/14',
      },
      date: '2018-10-18',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020093,
        link: '/api/v1/game/2018020093/feed/live',
        content: {
          link: '/api/v1/game/2018020093/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '13:04',
        assists: 1,
        goals: 0,
        pim: 7,
        shots: 1,
        games: 1,
        hits: 3,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:51',
        evenTimeOnIce: '11:54',
        penaltyMinutes: '7',
        faceOffPct: 50.0,
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:19',
        blocked: 0,
        plusMinus: 1,
        points: 1,
        shifts: 20,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 8,
        name: 'Montréal Canadiens',
        link: '/api/v1/teams/8',
      },
      date: '2018-10-15',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020075,
        link: '/api/v1/game/2018020075/feed/live',
        content: {
          link: '/api/v1/game/2018020075/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '14:39',
        assists: 1,
        goals: 0,
        pim: 0,
        shots: 0,
        games: 1,
        hits: 1,
        powerPlayGoals: 0,
        powerPlayPoints: 1,
        powerPlayTimeOnIce: '02:33',
        evenTimeOnIce: '12:06',
        penaltyMinutes: '0',
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: -1,
        points: 1,
        shifts: 21,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 6,
        name: 'Boston Bruins',
        link: '/api/v1/teams/6',
      },
      date: '2018-10-13',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020061,
        link: '/api/v1/game/2018020061/feed/live',
        content: {
          link: '/api/v1/game/2018020061/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '16:51',
        assists: 1,
        goals: 0,
        pim: 0,
        shots: 0,
        games: 1,
        hits: 4,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:51',
        evenTimeOnIce: '14:00',
        penaltyMinutes: '0',
        faceOffPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: 1,
        points: 1,
        shifts: 19,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 10,
        name: 'Toronto Maple Leafs',
        link: '/api/v1/teams/10',
      },
      date: '2018-10-11',
      isHome: true,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020052,
        link: '/api/v1/game/2018020052/feed/live',
        content: {
          link: '/api/v1/game/2018020052/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '14:58',
        assists: 0,
        goals: 1,
        pim: 0,
        shots: 2,
        games: 1,
        hits: 0,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '00:52',
        evenTimeOnIce: '14:05',
        penaltyMinutes: '0',
        faceOffPct: 0.0,
        shotPct: 50.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:01',
        blocked: 1,
        plusMinus: 1,
        points: 1,
        shifts: 19,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 24,
        name: 'Anaheim Ducks',
        link: '/api/v1/teams/24',
      },
      date: '2018-10-08',
      isHome: false,
      isWin: false,
      isOT: true,
      game: {
        gamePk: 2018020035,
        link: '/api/v1/game/2018020035/feed/live',
        content: {
          link: '/api/v1/game/2018020035/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '14:36',
        assists: 0,
        goals: 0,
        pim: 6,
        shots: 1,
        games: 1,
        hits: 4,
        powerPlayGoals: 0,
        powerPlayPoints: 0,
        powerPlayTimeOnIce: '02:39',
        evenTimeOnIce: '11:57',
        penaltyMinutes: '6',
        shotPct: 0.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 0,
        plusMinus: -1,
        points: 0,
        shifts: 21,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 26,
        name: 'Los Angeles Kings',
        link: '/api/v1/teams/26',
      },
      date: '2018-10-07',
      isHome: false,
      isWin: false,
      isOT: false,
      game: {
        gamePk: 2018020031,
        link: '/api/v1/game/2018020031/feed/live',
        content: {
          link: '/api/v1/game/2018020031/content',
        },
      },
    }, {
      season: '20182019',
      stat: {
        timeOnIce: '11:37',
        assists: 0,
        goals: 1,
        pim: 2,
        shots: 1,
        games: 1,
        hits: 1,
        powerPlayGoals: 1,
        powerPlayPoints: 1,
        powerPlayTimeOnIce: '01:28',
        evenTimeOnIce: '10:09',
        penaltyMinutes: '2',
        faceOffPct: 50.0,
        shotPct: 100.0,
        gameWinningGoals: 0,
        overTimeGoals: 0,
        shortHandedGoals: 0,
        shortHandedPoints: 0,
        shortHandedTimeOnIce: '00:00',
        blocked: 2,
        plusMinus: 0,
        points: 1,
        shifts: 14,
      },
      team: {
        id: 17,
        name: 'Detroit Red Wings',
        link: '/api/v1/teams/17',
      },
      opponent: {
        id: 29,
        name: 'Columbus Blue Jackets',
        link: '/api/v1/teams/29',
      },
      date: '2018-10-04',
      isHome: true,
      isWin: false,
      isOT: true,
      game: {
        gamePk: 2018020010,
        link: '/api/v1/game/2018020010/feed/live',
        content: {
          link: '/api/v1/game/2018020010/content',
        },
      },
    }],
  }],
};

export default data;
